# Generated by Django 3.2.12 on 2022-11-30 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0016_auto_20221130_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assigntime',
            name='period',
            field=models.CharField(choices=[('10:00 - 10:50', '10:00 - 10:50'), ('10:50 - 11:40', '10:50 - 11:40'), ('11:40 - 12:30', '11:40 - 12:30'), ('12:30 - 1:20', '12:30 - 1:20'), ('1:40 - 2:30', '1:40 - 2:30'), ('2:30 - 3:20', '2:30 - 3:20'), ('3:20 - 4:10', '3:20 - 4:10'), ('4:10 - 5:00', '4:10 - 5:00')], default='11:00 - 11:50', max_length=50),
        ),
    ]
