# Generated by Django 3.2.12 on 2022-11-30 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0017_alter_assigntime_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assigntime',
            name='period',
            field=models.CharField(choices=[('10:00 - 10:45', '10:00 - 10:45'), ('10:45 - 11:30', '10:45 - 11:30'), ('11:30 - 12:15', '11:30 - 12:15'), ('12:15 - 1:15', '12:15 - 1:15'), ('1:15 - 2;00', '1:15 - 2:00'), ('2:00 - 2:45', '2:00 - 2:45'), ('2:45 - 3:30', '2:45 - 3:30'), ('3:30 - 4:15', '3:30 - 4:15'), ('4:15 - 5:00', '4:15 - 5:00')], default='11:00 - 11:50', max_length=50),
        ),
    ]
